services:
  backend:
    build: ./notificationsystem
    container_name: cns-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-ab9a776-singhtanishq288-ba1e.i.aivencloud.com:11263/defaultdb?ssl-mode=REQUIRED
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_Au69xHYHORBOBNmHJNO

  frontend:
    build: ./cns-frontend
    container_name: cns-frontend
    ports:
      - "3000:80"
