services:
  backend:
    build: ./notificationsystem
    container_name: cns-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-ab9a776-singhtanishq288-ba1e.i.aivencloud.com:11263/defaultdb?ssl-mode=REQUIRED
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_Au69xHYHORBOBNmHJNO
      DROPBOX_ACCESS_TOKEN: sl.u.AGMaPgZiMqk24Q77RfOotGTf6176l2fe3PCtpc2vcLEHzPmLZZ0lBU_xG0piMlPTUCYryJWW3rJJQdu7bScTAzRouJetgU8wegnOoXJCRxdf5di475FsK8UqtLG8SqnTRaDanVfVbxDgZJ7slRE4XcmiLcFeLgCsQJEpG-4L4pXbeFOYiIbQvujFDoBa1C5qB3USWJQCMmXciTT21TD0ASje7KG7E9ZJPvk1tRseJ4m00tYhIaSTFAdY9Cpi4Z1QuV9FlTD9ifAGoQdWZahQRa022cawmj2Pc8iSFcorK1q7aZcQZ-YnV4x6fp4IAx1K_f83tKHKX5EAiiB5DF_Fe4VX3-mit_-BOWDlAx91JbwhRI7DY2WgHy70VQ9GgztUKYN0u29cv0ekpVTgJD_1GCEA1ognahH3dMqA1ptdH8-RI_yXp2hXmfukBIZkHzrJ1m8JoeWNiKLTofJTav8G1ljQaA5biWJDLpuPcRaJxADr9sRj9yhng_TbPIgJhPoy7m05PBxKXdg_Zm-PO_OdAmfmkDoeUx3tM7xRmopODICDLrH0HJ5toR8jEPC2mWEZBbmrgKVJDrNCkwOveZFLwTVH1Klce9ibCwONCgX1IM2eK6Ol3cltfwwt4zb9lddOseYDqI_DxIEp_wpiEyPxJrFg359XOvqguC_u4busGAvHVK3Az3-0hzDby_pgAqwFwrwXMt36-Z5S5NDwrXF2jBOCttLHtyF-meUJ0GU5YuoQAg4oaw5SrNxICXMMALdqxfSPsAjOO98wjobwXPGTUvDAs9bjf_eUEOrxYpMYPrphWkrUL5vVo3aaWyqaJgFyuppFXkQRmS5InQ8DhobdQxFnF9WgGijteub7jDGWrPdqaukp7b-jg2P0DP27kwJ_S-fMrCJkUc26FWpyyVq-_JYs8Pfb3PGvHxECyky0348dd45Wbh7jxVmSdjIWR9Vyiw2mqkAF9AlfqhPRX-F0DFdY06KUV93NKqYD8DPGchvJ3KgS-rjJWInScI5f5JqHyX1GZpd6PWkEsjog53izYb8hOQk4Y5A0llkdFAlA6W14B6OGtr34moEGvkAiNBzecyDeF1wYes8BAGDt0GVLejtqCbj58uuxTYVvhiX81wTmROQ8BkImHaYCqUL27h5ztw5fnLAjpHyU_9g6uS82-XzuEC90s_mVcy69z9vAAdMzXFD6sQJxlSQUuLwHeD57hIQRt-UvHEvRt86vttSOdqzB2Mjirt6iHR-xinxHKhmjjlI4EAiJstYNsMD_Q8mlfZtNoNFBQNQT9ofM-lk_My6hJtMm30aQiXv8YVs2rIYf85YrPKY4w6JUB2-f_jTUVhGC3P8MgLNUx_MsMuGzD_KSNwbDaL0QPd9ATXpmoQFFjSWy_6j2cL6MYamSNxXu1lKE0t6SIhByI1iPWRruyLHADnILjPOgTgBIxpVpOibN_Q
      DROPBOX_FOLDER: /notices

  frontend:
    build: ./cns-frontend
    container_name: cns-frontend
    ports:
      - "3000:80"
